### PR TITLE
add support for custom format display name

### LINKED ISSUE #35: Feature request: optional user-specified `format-display-name`
I'd like to have a way how to set custom `format-display-name` (in my dev builds).

My namespaces are quite long and this would be a centralized way how to strip common prefix from component names. Also one could apply app-specific knowlege on forming component names.

### PR DESCRIPTION
**Pull request by darwin**
Resolves #35

### CODE REVIEW

**Review by roman01la — COMMENTED** [review]
Thanks for adding tests. Would it make sense to not pass default fmt fn into a custom one and instead let users use default function explicitly by requiring it, if they need it?

**Comment by darwin** [comment]
I considered it and it would be prone to breaking if you decided/needed to rename or modify the function in uix. Or theoretically in the future this gives you more flexibility, you alter internal function but feed `*format-display-name*` with old version for backward compatibility.

But I'm ok either way. If you want me to remove it.
I also considered passin a map with options as second argument, if we wanted to extend it in the future. e.g. pass original f for possible inspection.

**Comment by roman01la** [comment]
I'm not opposed to it. Thanks for explaining, it's more clear to me now.

**Comment by darwin** [comment]
Or we could set `default-format-display-name` as default value of `*format-display-name*`. And people would be responsible for chaining it. This would be maybe more consistent.

**Pull request merged**
